.\"             -*-Nroff-*-
.\"
.TH "wayinfo" 1 "18 Nov 2025" "wayinfo" "User Commands"
.SH NAME
wayinfo \- output information about the current Wayland setup
.SH SYNOPSIS
.B wayinfo
[options]
.sp
.SH DESCRIPTION
wayinfo displays information about the current Wayland display server setup, including compositor details, display properties, and other Wayland-specific configuration information.
.sp
.SH OPTIONS
.sp
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.3
.SH AUTHOR
.B wayinfo
was written by Alexander F. Rødseth <xyproto@archlinux.org>