.\"             -*-Nroff-*-
.\"
.TH "lswallpaper" 1 "23 Jul 2025" "lswallpaper" "User Commands"
.SH NAME
lswallpaper \- list all wallpapers on the system
.SH SYNOPSIS
.B lswallpaper
[options]
.sp
.SH DESCRIPTION
lswallpaper searches the system for wallpaper images and displays them. It can find wallpapers in common directories and identify which ones are part of collections.
.sp
.SH OPTIONS
.sp
.TP
.B \-l or \-\-long
Also list full paths to wallpapers.
.TP
.B \-s or \-\-star
Prefix wallpapers with a star if they are part of a collection.
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.0
.SH AUTHOR
.B lswallpaper
was written by Alexander F. Rødseth <xyproto@archlinux.org>