.\"             -*-Nroff-*-
.\"
.TH "timedinfo" 1 "18 Nov 2025" "timedinfo" "User Commands"
.SH NAME
timedinfo \- show information about timed wallpapers on the system
.SH SYNOPSIS
.B timedinfo
[options] [name]
.sp
.SH DESCRIPTION
timedinfo displays detailed information about timed wallpapers available on the system. It can show metadata, timing information, and other properties of timed wallpaper files.
.sp
.SH OPTIONS
.sp
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.3
.SH AUTHOR
.B timedinfo
was written by Alexander F. Rødseth <xyproto@archlinux.org>