.\"             -*-Nroff-*-
.\"
.TH "lscollection" 1 "23 Jul 2025" "lscollection" "User Commands"
.SH NAME
lscollection \- list all wallpaper collections on the system
.SH SYNOPSIS
.B lscollection
[options]
.sp
.SH DESCRIPTION
lscollection searches the system for wallpaper collections and displays them. Collections are groups of related wallpapers that can be used together.
.sp
.SH OPTIONS
.sp
.TP
.B \-l or \-\-long
Also list collection type and full path.
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.2
.SH AUTHOR
.B lscollection
was written by Alexander F. Rødseth <xyproto@archlinux.org>