.\"             -*-Nroff-*-
.\"
.TH "vram" 1 "12 Sep 2022" "vram" "User Commands"
.SH NAME
vram \- get the average VRAM for all available GPUs
.SH SYNOPSIS
.B vram
Display the average VRAM of all available GPUs.
.sp
.SH DESCRIPTION
vram can fetch information about all available GPUs.
.sp
.SH OPTIONS
.sp
.TP
.B \-l or \-\-list
List the VRAM information for all available GPUs.
.TP
.B \-h or \-\-help
Show usage information.
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.12.0
.SH AUTHOR
.B o
was written by Alexander F. Rødseth <xyproto@archlinux.org>
