.\"             -*-Nroff-*-
.\"
.TH "vram" 1 "23 Jul 2025" "vram" "User Commands"
.SH NAME
vram \- get the minimum amount of VRAM for all non-integrated GPUs, or list all GPUs
.SH SYNOPSIS
.B vram
Display the minimum amount of available VRAM of all available non-integrated GPUs.
.sp
If only non-integrated GPUs are found, the minimum amount of VRAM for those is used instead.
.sp
.SH DESCRIPTION
vram can fetch information about all available GPUs.
.sp
.SH OPTIONS
.sp
.TP
.B \-l or \-\-list
List the bus ID, a description and available VRAM, for all GPUs.
.TP
.B \-i or \-\-integrated
Find the minimum amount of VRAM for all GPUs, including integrated ones.
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.0
.SH AUTHOR
.B vram
was written by Alexander F. Rødseth <xyproto@archlinux.org>
