#!/bin/bash -e
filename="$1"

if [[ "$1" == "" ]]; then
  echo 'Usage: heic-install image.heic'
  exit 1
fi

# pkgdir is optional
pkgdir="$2"

baseName=$(basename "$filename")
name=${baseName%.*}

if [[ "$name" == "" ]]; then
  echo 'The image name is empty'
  exit 1
fi

# check if we have access to /usr/share/backgrounds (since -e is used)
install -d "$pkgdir/usr/share/backgrounds/$name" || \
  (echo 'heic-install needs permissions to write to /usr/share/backgrounds, try "sudo heic-install"'; exit 1)

# extract the metadata
echo -n "--> Extracting metadata from $baseName... "
heic2stw -- "$filename" > "$pkgdir/usr/share/backgrounds/$name/$name.stw" && echo DONE || exit 1

# convert the images
echo -n '--> Converting images from HEIC to JPG...'
convert -verbose -- "$filename" "$pkgdir/usr/share/backgrounds/$name/%02d.jpg" && echo '--> DONE' || exit 1

# set permissions
chmod 0644 "$pkgdir/usr/share/backgrounds/$name/"*

# check if it shows up with lstimed
lstimed | grep -q "$name" && echo "--> Success, $name was installed" || (echo "Error, $name was not installed correctly"; exit 1)
