.\"             -*-Nroff-*-
.\"
.TH "heic2stw" 1 "23 Jul 2025" "heic2stw" "User Commands"
.SH NAME
heic2stw \- convert from GNOME Timed Wallpaper to the Simple Timed Wallpaper format
.SH SYNOPSIS
.B heic2stw
[options] [HEIC file]
.sp
.SH DESCRIPTION
heic2stw converts HEIC dynamic wallpaper files to the Simple Timed Wallpaper (STW) format, which can be used with timed wallpaper systems.
.sp
.SH OPTIONS
.sp
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.1
.SH AUTHOR
.B heic2stw
was written by Alexander F. Rødseth <xyproto@archlinux.org>