.\"             -*-Nroff-*-
.\"
.TH "xml2stw" 1 "23 Jul 2025" "xml2stw" "User Commands"
.SH NAME
xml2stw \- convert from GNOME Timed Wallpaper to the Simple Timed Wallpaper format
.SH SYNOPSIS
.B xml2stw
[options] [XML file]
.sp
.SH DESCRIPTION
xml2stw converts GNOME timed wallpaper XML files to the Simple Timed Wallpaper (STW) format. This allows GNOME timed wallpapers to be used with other wallpaper systems that support the STW format.
.sp
.SH OPTIONS
.sp
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.13.0
.SH AUTHOR
.B xml2stw
was written by Alexander F. Rødseth <xyproto@archlinux.org>