.\"             -*-Nroff-*-
.\"
.TH "setcollection" 1 "18 Nov 2025" "setcollection" "User Commands"
.SH NAME
setcollection \- change the desktop wallpaper
.SH SYNOPSIS
.B setcollection
[options] [name of wallpaper collection]
.sp
.SH DESCRIPTION
setcollection changes the desktop wallpaper by selecting from a named wallpaper collection. Collections are groups of related wallpapers that can be applied as a set.
.sp
.SH OPTIONS
.sp
.TP
.B \-v or \-\-verbose
Enable verbose output showing detailed information about the operation.
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.3
.SH AUTHOR
.B setcollection
was written by Alexander F. Rødseth <xyproto@archlinux.org>