.\"             -*-Nroff-*-
.\"
.TH "xinfo" 1 "23 Jul 2025" "xinfo" "User Commands"
.SH NAME
xinfo \- output information about the current X setup
.SH SYNOPSIS
.B xinfo
[options]
.sp
.SH DESCRIPTION
xinfo displays information about the current X Window System setup, including X server details, display properties, screen information, and other X11-specific configuration data.
.sp
.SH OPTIONS
.sp
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.1
.SH AUTHOR
.B xinfo
was written by Alexander F. Rødseth <xyproto@archlinux.org>