.\"             -*-Nroff-*-
.\"
.TH "lsmon" 1 "23 Jul 2025" "lsmon" "User Commands"
.SH NAME
lsmon \- output ID, width and height for all connected monitors
.SH SYNOPSIS
.B lsmon
[options]
.sp
.SH DESCRIPTION
lsmon displays information about all connected monitors, including their ID numbers, resolution (width and height), and optionally their DPI values.
.sp
.SH OPTIONS
.sp
.TP
.B \-d or \-\-dpi
Also output the monitor DPI (dots per inch).
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.0
.SH AUTHOR
.B lsmon
was written by Alexander F. Rødseth <xyproto@archlinux.org>