.\"             -*-Nroff-*-
.\"
.TH "lstimed" 1 "23 Jul 2025" "lstimed" "User Commands"
.SH NAME
lstimed \- list all timed wallpapers on the system
.SH SYNOPSIS
.B lstimed
[options]
.sp
.SH DESCRIPTION
lstimed searches the system for timed wallpapers and displays them. Timed wallpapers change automatically based on time of day or other scheduling rules.
.sp
.SH OPTIONS
.sp
.TP
.B \-l or \-\-long
Also list paths and the number of timed events.
.TP
.B \-V or \-\-version
Show the current version.
.PP
.SH VERSION
5.14.2
.SH AUTHOR
.B lstimed
was written by Alexander F. Rødseth <xyproto@archlinux.org>